version: '2'
services:
  horariovpn-app:
    image: horariovpn
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@horariovpn-oracle:1521:horarioVPN
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8090:8090
